### ISSUE TITLE
zef install PDF test fail

### ISSUE THREAD

**Issue by librasteve** [pdf-raku/PDF-raku#28]
===> Searching for: PDF
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Searching for missing dependencies: Compress::Zlib, PDF::Grammar:ver<0.2.1+>
===> Searching for missing dependencies: Compress::Zlib::Raw
===> Testing: Compress::Zlib::Raw:ver<1.0.1>:auth<github:retupmoca>
===> Testing [OK] for Compress::Zlib::Raw:ver<1.0.1>:auth<github:retupmoca>
===> Testing: Compress::Zlib:ver<1.1.0>:auth<github:retupmoca>
===> Testing [OK] for Compress::Zlib:ver<1.1.0>:auth<github:retupmoca>
===> Testing: PDF::Grammar:ver<0.2.4>:auth<github:pdf-raku>:api<PDF.1.7>
[PDF::Grammar] # loading t/helloworld.pdf (set $TEST_PDF to override)
===> Testing [OK] for PDF::Grammar:ver<0.2.4>:auth<github:pdf-raku>:api<PDF.1.7>
===> Testing: PDF:ver<0.4.4>:auth<github:pdf-raku>:api<PDF.1.7>
===> Testing [FAIL]: PDF:ver<0.4.4>:auth<github:pdf-raku>:api<PDF.1.7>
Aborting due to test failure: PDF:ver<0.4.4>:auth<github:pdf-raku>:api<PDF.1.7> (use --force-test to override)

stephenroe@Jester raku % raku -v
Welcome to 𝐑𝐚𝐤𝐮𝐝𝐨™ v2020.10.
Implementing the 𝐑𝐚𝐤𝐮™ programming language v6.d.
Built on MoarVM version 2020.10.

on macOS Catalina 10.15.7 (19H15)

stephenroe@Jester raku % zef --verbose install PDF                     
===> Searching for: PDF
===> Found: PDF:ver<0.4.4>:auth<github:pdf-raku>:api<PDF.1.7> [via Zef::Repository::LocalCache]
===> Searching for missing dependencies: PDF::Grammar:ver<0.2.1+>
===> Found dependencies: PDF::Grammar:ver<0.2.4>:auth<github:pdf-raku>:api<PDF.1.7>, PDF::Grammar:ver<0.2.4>:auth<github:pdf-raku>:api<PDF.1.7> [via Zef::Repository::LocalCache]
===> Testing: PDF::Grammar:ver<0.2.4>:auth<github:pdf-raku>:api<PDF.1.7>
[PDF::Grammar] t/00objects.t ....... ok
[PDF::Grammar] t/content-ops.t ..... ok
[PDF::Grammar] t/content-parse.t ... ok
[PDF::Grammar] t/fdf-parse.t ....... ok
[PDF::Grammar] t/function-parse.t .. ok
[PDF::Grammar] t/pdf-components.t .. ok
[PDF::Grammar] t/pdf-objects.t ..... ok
[PDF::Grammar] # loading t/helloworld.pdf (set $TEST_PDF to override)
[PDF::Grammar] t/pdf-parsefile.t ... ok
[PDF::Grammar] t/pdf-regex.t ....... ok
[PDF::Grammar] All tests successful.
[PDF::Grammar] Files=9, Tests=602, 10 wallclock secs ( 0.17 usr  0.05 sys + 14.11 cusr  1.01 csys = 15.34 CPU)
[PDF::Grammar] Result: PASS
===> Testing [OK] for PDF::Grammar:ver<0.2.4>:auth<github:pdf-raku>:api<PDF.1.7>
===> Testing: PDF:ver<0.4.4>:auth<github:pdf-raku>:api<PDF.1.7>
[PDF] t/00-helloworld.t ...... ok
[PDF] t/01-readme.t .......... ok
[PDF] t/cos-coerce.t ......... ok
[PDF] t/cos-date-string.t .... ok
[PDF] t/cos-deref.t .......... ok
[PDF] t/cos-text-string.t .... ok
[PDF] t/cos-tie-entry.t ...... ok
[PDF] t/cos-tie-index.t ...... ok
[PDF] t/cos-tie.t ............ ok
[PDF] t/cos-type-info.t ...... ok
[PDF] t/cos-type-objstm.t .... ok
[PDF] t/cos-type-xref.t ...... ok
[PDF] t/cos-util.t ........... ok
[PDF] t/filter-ascii85.t ..... ok
[PDF] t/filter-asciihex.t .... ok
[PDF] t/filter-flate.t ....... ok
[PDF] t/filter-lzw.t ......... ok
[PDF] t/filter-predictors.t .. ok
[PDF] t/filter-runlength.t ... ok
[PDF] t/filter.t ............. ok
[PDF] t/indobj-array.t ....... ok
[PDF] t/indobj-bool.t ........ ok
[PDF] t/indobj-dict.t ........ ok
[PDF] t/indobj-name.t ........ ok
[PDF] t/indobj-null.t ........ ok
[PDF] t/indobj-num.t ......... ok
[PDF] t/indobj-stream.t ...... ok
[PDF] t/indobj-string.t ...... ok
[PDF] t/indobj.t ............. ok
[PDF] t/io-crypt.t ........... 
[PDF] No subtests run 
[PDF] t/io-serialize.t ....... ok
[PDF] t/io-util.t ............ ok
[PDF] t/io.t ................. ok
[PDF] t/pdf-cos.t ............ ok
[PDF] t/pdf-crypt-aes.t ...... 
[PDF] Failed 10/10 subtests 
[PDF] t/pdf-crypt-rc4.t ...... 
[PDF] Failed 17/17 subtests 
[PDF] t/pdf-open.t ........... 
[PDF] All 10 subtests passed 
[PDF] t/pdf-reencrypt.t ...... 
[PDF] Failed 6/6 subtests 
[PDF] t/read-fdf.t ........... ok
[PDF] t/read-pdf.t ........... ok
[PDF] t/reader-deref.t ....... ok
[PDF] t/reader-exceptions.t .. ok
[PDF] t/update-encrypted.t ... 
[PDF] Failed 5/5 subtests 
[PDF] t/update.t ............. ok
[PDF] t/write-ast.t .......... ok
[PDF] t/write-indobj.t ....... ok
[PDF] t/write-pdf.t .......... ok
[PDF] Test Summary Report
[PDF] -------------------
[PDF] t/io-crypt.t         (Wstat: 6 Tests: 0 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: No plan found in TAP output
[PDF] t/pdf-crypt-aes.t    (Wstat: 6 Tests: 0 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: Bad plan.  You planned 10 tests but ran 0.
[PDF] t/pdf-crypt-rc4.t    (Wstat: 6 Tests: 0 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: Bad plan.  You planned 17 tests but ran 0.
[PDF] t/pdf-open.t         (Wstat: 6 Tests: 10 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: No plan found in TAP output
[PDF] t/pdf-reencrypt.t    (Wstat: 6 Tests: 0 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: Bad plan.  You planned 6 tests but ran 0.
[PDF] t/update-encrypted.t (Wstat: 6 Tests: 0 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: Bad plan.  You planned 5 tests but ran 0.
[PDF] Files=47, Tests=839, 144 wallclock secs ( 0.36 usr  0.14 sys + 216.07 cusr 24.04 csys = 240.61 CPU)
[PDF] Result: FAIL
===> Testing [FAIL]: PDF:ver<0.4.4>:auth<github:pdf-raku>:api<PDF.1.7>
Aborting due to test failure: PDF:ver<0.4.4>:auth<github:pdf-raku>:api<PDF.1.7> (use --force-test to override)

**Comment by dwarring** [comment]
I just enabled Travis testing on osx. It's failing on OpenSSL dependencies. https://travis-ci.org/github/pdf-raku/PDF-raku/jobs/747686408. OpenSSL is used for encryption, which is what is failing here.

@p6steve are you able to retest or reinstall OpenSSL?

**Comment by librasteve** [comment]
Hi David - I'm happy to assist - what is the stable version of openssl that you develop to? I would rather avoid the new openssl 3.0 alpha for now... my kit is currently LibreSSL 2.8.3 fyi

**Comment by librasteve** [comment]
OK - I upgraded to
OpenSSL 1.1.1h  22 Sep 2020
(had to workaround macOS constraints detailed here 
https://stackoverflow.com/questions/62195898/openssl-still-pointing-to-libressl-2-8-3)

Still fails, I'm afraid
[PDF] t/indobj.t ............. ok
[PDF] t/io-crypt.t ........... 
[PDF] No subtests run 
[PDF] t/io-serialize.t ....... ok
[PDF] t/io-util.t ............ ok
[PDF] t/io.t ................. ok
[PDF] t/pdf-cos.t ............ ok
[PDF] t/pdf-crypt-aes.t ...... 
[PDF] Failed 10/10 subtests 
[PDF] t/pdf-crypt-rc4.t ...... 
[PDF] Failed 17/17 subtests 
[PDF] t/pdf-open.t ........... 
[PDF] All 10 subtests passed 
[PDF] t/pdf-reencrypt.t ...... 
[PDF] Failed 6/6 subtests 
[PDF] t/read-fdf.t ........... ok
[PDF] t/read-pdf.t ........... ok
[PDF] t/reader-deref.t ....... ok
[PDF] t/reader-exceptions.t .. ok
[PDF] t/update-encrypted.t ... 
[PDF] Failed 5/5 subtests 
[PDF] t/update.t ............. ok
[PDF] t/write-ast.t .......... ok
[PDF] t/write-indobj.t ....... ok
[PDF] t/write-pdf.t .......... ok
[PDF] Test Summary Report
[PDF] -------------------
[PDF] t/io-crypt.t         (Wstat: 6 Tests: 0 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: No plan found in TAP output
[PDF] t/pdf-crypt-aes.t    (Wstat: 6 Tests: 0 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: Bad plan.  You planned 10 tests but ran 0.
[PDF] t/pdf-crypt-rc4.t    (Wstat: 6 Tests: 0 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: Bad plan.  You planned 17 tests but ran 0.
[PDF] t/pdf-open.t         (Wstat: 6 Tests: 10 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: No plan found in TAP output
[PDF] t/pdf-reencrypt.t    (Wstat: 6 Tests: 0 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: Bad plan.  You planned 6 tests but ran 0.
[PDF] t/update-encrypted.t (Wstat: 6 Tests: 0 Failed: 0)
[PDF]   Non-zero wait status: 6
[PDF]   Parse errors: Bad plan.  You planned 5 tests but ran 0.
[PDF] Files=47, Tests=839, 113 wallclock secs ( 0.31 usr  0.13 sys + 171.42 cusr 18.87 csys = 190.73 CPU)
[PDF] Result: FAIL
===> Testing [FAIL]: PDF:ver<0.4.4>:auth<github:pdf-raku>:api<PDF.1.7>
Aborting due to test failure: PDF:ver<0.4.4>:auth<github:pdf-raku>:api<PDF.1.7> (use --force-test to override)

**Comment by dwarring** [comment]
Hi @p6steve,
Sorry I meant the Raku bindings not the OpenSSL library itself. Does the module reinstall without errors?

Seems at least that the failures are somehow related to PDF's use of OpenSSL for encryption.

I'm running on Debian 10 with OpenSSL library 1.1.1d and OpenSSL Raku bindings 0.1.23.

**Comment by librasteve** [comment]
Yes - still failing (see verbose log above) - using raku binding OpenSSL 0.1.23.

**Comment by dwarring** [comment]
Does the raku OpenSSL module reinstall without failures?

**Comment by librasteve** [comment]
ahh - ok I tried this `zef --verbose install OpenSSL` where this ```
which openssl /usr/local/opt/openssl@1.1/bin/openssl
```

and got this... (see below)

My SWAG is that there is some subtle macOS issue with raku OpenSSL ...  but this is beyond me to fix and I am a bit worried about breaking my ssl kit. Advice needed, please...

===> Searching for: OpenSSL
===> Found: OpenSSL:ver<0.1.23>:auth<github:sergot> [via Zef::Repository::LocalCache]
===> Testing: OpenSSL:ver<0.1.23>:auth<github:sergot>
[OpenSSL] t/01-basic.t ........... 
[OpenSSL] No subtests run 
[OpenSSL] t/02-socket.t .......... 
[OpenSSL] No subtests run 
[OpenSSL] t/03-rsa.t ............. 
[OpenSSL] No subtests run 
[OpenSSL] t/04-crypt.t ........... 
[OpenSSL] Failed 10/11 subtests 
[OpenSSL] t/05-digest.t .......... 
[OpenSSL] Failed 5/5 subtests 
[OpenSSL] t/06-digest-md5.t ...... 
[OpenSSL] Failed 1/1 subtests 
[OpenSSL] t/07-version.t ......... 
[OpenSSL] Failed 9/9 subtests 
[OpenSSL] t/10-client-ca-file.t .. 
[OpenSSL] No subtests run 
[OpenSSL] t/15-issue-36.t ........ 
[OpenSSL] No subtests run 
[OpenSSL] Test Summary Report
[OpenSSL] -------------------
[OpenSSL] t/01-basic.t         (Wstat: 6 Tests: 0 Failed: 0)
[OpenSSL]   Non-zero wait status: 6
[OpenSSL]   Parse errors: No plan found in TAP output
[OpenSSL] t/02-socket.t        (Wstat: 6 Tests: 0 Failed: 0)
[OpenSSL]   Non-zero wait status: 6
[OpenSSL]   Parse errors: No plan found in TAP output
[OpenSSL] t/03-rsa.t           (Wstat: 6 Tests: 0 Failed: 0)
[OpenSSL]   Non-zero wait status: 6
[OpenSSL]   Parse errors: No plan found in TAP output
[OpenSSL] t/04-crypt.t         (Wstat: 6 Tests: 1 Failed: 0)
[OpenSSL]   Non-zero wait status: 6
[OpenSSL]   Parse errors: Bad plan.  You planned 11 tests but ran 1.
[OpenSSL] t/05-digest.t        (Wstat: 6 Tests: 0 Failed: 0)
[OpenSSL]   Non-zero wait status: 6
[OpenSSL]   Parse errors: Bad plan.  You planned 5 tests but ran 0.
[OpenSSL] t/06-digest-md5.t    (Wstat: 6 Tests: 0 Failed: 0)
[OpenSSL]   Non-zero wait status: 6
[OpenSSL]   Parse errors: Bad plan.  You planned 1 tests but ran 0.
[OpenSSL] t/07-version.t       (Wstat: 6 Tests: 0 Failed: 0)
[OpenSSL]   Non-zero wait status: 6
[OpenSSL]   Parse errors: Bad plan.  You planned 9 tests but ran 0.
[OpenSSL] t/10-client-ca-file.t (Wstat: 6 Tests: 0 Failed: 0)
[OpenSSL]   Non-zero wait status: 6
[OpenSSL]   Parse errors: No plan found in TAP output
[OpenSSL] t/15-issue-36.t      (Wstat: 6 Tests: 0 Failed: 0)
[OpenSSL]   Non-zero wait status: 6
[OpenSSL]   Parse errors: No plan found in TAP output
[OpenSSL] Files=9, Tests=1, 40 wallclock secs ( 0.06 usr  0.03 sys + 42.96 cusr  6.72 csys = 49.77 CPU)
[OpenSSL] Result: FAIL
===> Testing [FAIL]: OpenSSL:ver<0.1.23>:auth<github:sergot>
Aborting due to test failure: OpenSSL:ver<0.1.23>:auth<github:sergot> (use --force-test to override)

**Comment by dwarring** [comment]
Looks like this [open OpenSSL issue](https://github.com/sergot/openssl/issues/80)

**Comment by dwarring** [comment]
Hi @p6steve, do you still have an issue installing with latest OpenSSL?

**Comment by librasteve** [comment]
Hi @dwarring - I continue to have a range of sporadic issue with raku/rakudo on M1 MacOS Monterey - my solution was to move to Docker Desktop and/or vftools (which is awesome).

At the risk of self promotion ;-) here is the blog I wrote that describes (at length) how to do all that - https://p6steve.wordpress.com/2021/11/18/raku-at-the-monterey-docks/

On ubuntu on vftools, zef install PDF is 100% fine (including auto install of all deps). I fear that this Issue is incorrectly pointing at PDF when there is a deeper (threading?) instability on macOS... so I will close it.

Last login: Sat Jan 22 14:23:32 2022 from 192.168.64.1
root@ubuntu:~# zef info PDF
===> Updating fez mirror: https://360.zef.pm/
===> Updated fez mirror: https://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
- Info for: PDF
- Identity: PDF:ver<0.4.19>:auth<cpan:WARRINGD>
- Recommended By: Zef::Repository::Ecosystems<cpan>
- Installed: No
Description:	 Base classes for reading, manipulation and writing of PDF data
License:	 Artistic-2.0
Source-url:	 http://www.cpan.org/authors/id/W/WA/WARRINGD/Perl6/PDF-0.4.19.tar.gz
Provides: 44 modules
Depends: 6 items
root@ubuntu:~# zef install PDF
===> Searching for: PDF
===> Updating fez mirror: https://360.zef.pm/
===> Updated fez mirror: https://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Searching for missing dependencies: Compress::Zlib, Hash::int, Method::Also, PDF::Grammar:ver<0.2.1+>
===> Searching for missing dependencies: Compress::Zlib::Raw
===> Testing: Compress::Zlib::Raw:ver<1.0.1>
===> Testing [OK] for Compress::Zlib::Raw:ver<1.0.1>
===> Testing: Compress::Zlib:ver<1.1.0>
===> Testing [OK] for Compress::Zlib:ver<1.1.0>
===> Testing: Hash::int:ver<0.0.5>:auth<zef:lizmat>
===> Testing [OK] for Hash::int:ver<0.0.5>:auth<zef:lizmat>
===> Testing: Method::Also:ver<0.0.7>:auth<zef:lizmat>
===> Testing [OK] for Method::Also:ver<0.0.7>:auth<zef:lizmat>
===> Testing: PDF::Grammar:ver<0.2.6>:auth<cpan:WARRINGD>
# loading t/helloworld.pdf (set $TEST_PDF to override)
===> Testing [OK] for PDF::Grammar:ver<0.2.6>:auth<cpan:WARRINGD>
===> Testing: PDF:ver<0.4.19>:auth<cpan:WARRINGD>
===> Testing [OK] for PDF:ver<0.4.19>:auth<cpan:WARRINGD>
===> Installing: Compress::Zlib::Raw:ver<1.0.1>
===> Installing: Compress::Zlib:ver<1.1.0>
===> Installing: Hash::int:ver<0.0.5>:auth<zef:lizmat>
===> Installing: Method::Also:ver<0.0.7>:auth<zef:lizmat>
===> Installing: PDF::Grammar:ver<0.2.6>:auth<cpan:WARRINGD>
===> Installing: PDF:ver<0.4.19>:auth<cpan:WARRINGD>

1 bin/ script [pdf-rewriter.raku] installed to:
/usr/share/perl6/site/bin
